# Generated by Django 5.2.1 on 2025-05-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
